config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
  end

  root to: 'accounts#index'

  resources :accounts, only: [:index] do
    get :transactions, on: :member
  end

  resources :money_transfers, only: [:new, :create]
end

app/models/account.rb
class Account < ApplicationRecord
  # Associations
  belongs_to :user
  has_many :transactions

  # Validations
  validates :number, presence: true, uniqueness: true
  validates :user_id, presence: true

  # Callbacks
  before_validation :set_account_number, on: [:create]

  def balance
    Money.new(sum_of_credit_in_cents - sum_of_debit_in_cents)
  end

  private
  def sum_of_credit_in_cents
    transactions.credit.sum(:amount_cents)
  end

  def sum_of_debit_in_cents
    transactions.debit.sum(:amount_cents)
  end

  def set_account_number
    self.number ||= GenerateRandomCodeService.perform(self.class, :number)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/with_money_column.rb
module WithMoneyColumn
  extend ActiveSupport::Concern

  DEFAULT_MONEY_COLUMN_OPTIONS = {
    allow_nil: true,
    numericality: {
      greater_than_or_equal_to: 0,
      less_than_or_equal_to: 21_474_836
    },
    with_model_currency: :currency
  }.freeze

end

app/models/money_transfer.rb
class MoneyTransfer < ApplicationRecord
  include WithMoneyColumn

  # money attributes
  monetize :amount_cents, DEFAULT_MONEY_COLUMN_OPTIONS

  attr_accessor :account_number

  # Associations
  belongs_to :sender, class_name: 'Account', foreign_key: 'sender_id'
  belongs_to :receiver, class_name: 'Account', foreign_key: 'receiver_id'
  has_many :transactions

  # Validations
  validates :sender_id, :receiver_id, :amount_cents, :amount_currency, presence: true
  validates :amount_cents, numericality: { greater_than: 0 }
  validate  :receiver_is_different_than_sender
  validate  :sufficient_balance, on: :create

  private

  def sufficient_balance
    errors.add :base, :insufficient_balance if sender.balance < amount
  end

  def receiver_is_different_than_sender
    errors.add :base, :receiver_is_not_different_than_sender if sender_id == receiver_id
  end
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  include WithMoneyColumn

  enum transaction_type: { credit: 0, debit: 1 }

  # money attributes
  monetize :amount_cents, :updated_balance_cents, DEFAULT_MONEY_COLUMN_OPTIONS

  # Associations
  belongs_to :account
  belongs_to :money_transfer, optional: true

  # Validations
  validates :account_id, :amount_cents, :amount_currency, :transaction_type, presence: true

  # Callbacks
  before_validation :set_transaction_code, on: [:create]
  after_create :update_balance

  private

  def update_balance
    Transaction.unscoped { update_attribute(:updated_balance, account.balance) }
  end

  def set_transaction_code
    self.code ||= GenerateRandomCodeService.perform(self.class, :code)
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :validatable

  # Associations
  has_many :accounts

  # Validations
  validates :first_name, :last_name, presence: true
  validates :email, presence: true, uniqueness: { case_sensitive: false }

  # Callbacks
  after_create :create_account

  private

  def create_account
    accounts.create unless accounts.exists?
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :authenticate_user!

  def index
    @accounts = current_user.accounts
  end

  def transactions
    @account = current_user.accounts.find params[:id]
    @transactions = @account.transactions.order(created_at: :desc).page(page).per(per)
  end

  private

  def page
    params[:page] || 1
  end

  def per
    params[:per] || 30
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def authenticate_user!
    redirect_to new_user_session_url unless current_user.present?
  end
end

app/controllers/money_transfers_controller.rb
class MoneyTransfersController < ApplicationController
  before_action :authenticate_user!, :set_sender

  def new
    @money_transfer = MoneyTransfer.new sender_id: @sender.id
  end

  def create
    @money_transfer = MoneyTransfer.new permitted_params

    @receiver = Account.find_by number: permitted_params[:account_number]
    @money_transfer.receiver_id = @receiver.try(:id)

    if @money_transfer.valid?
      begin
        MoneyTransfer.transaction do
          @money_transfer.save!

          @sender.transactions.debit.create!(amount: @money_transfer.amount, money_transfer_id: @money_transfer.id)
          @receiver.transactions.credit.create!(amount: @money_transfer.amount, money_transfer_id: @money_transfer.id)

          flash[:notice] = 'Money transferred successfully!'
          redirect_to transactions_account_path(@sender)
        end
      rescue ActiveRecord::RecordInvalid
        flash.now[:error] = 'Make sure you have sufficient fund in your account.'
        render :new
      end
    else
      flash.now[:error] = @money_transfer.errors.full_messages.to_sentence
      render :new
    end
  end

  private

  def set_sender
    if action_name == 'new'
      raise ArgumentError, 'Account is not provided' if params[:sender_id].nil?
      @sender = current_user.accounts.find params[:sender_id]
    else
      @sender = current_user.accounts.find permitted_params[:sender_id]
    end
  end

  def permitted_params
    params.require(:money_transfer).permit(:sender_id, :account_number, :amount, :description)
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :authenticate_user!

  def index
    @accounts = current_user.accounts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/index.haml
.limiter
  .container-login100
    .wrap-login100
      .container
        %h2 My accounts
        %p This is a list of all your active accounts
        %table.table
          %thead
            %tr
              %th.text-center Account Number
              %th.text-center Balance
              %th.text-center Actions
          %tbody
            - @accounts.each do |account|
              %tr
                %td.text-center="##{account.number}"
                %td.text-center 10$
                %td.text-center
                  = link_to "Transactions", transactions_account_path(account), class: "btn btn-outline-info text-blue"
                  = link_to "Transfer Money", new_money_transfer_path(sender_id: account.id), class: "btn btn-outline-success text-green"

app/views/accounts/transactions.haml
.limiter
  .container-login100
    .wrap-login100
      .container
        %h2 Transactions
        %p= "account: ##{@account.number}"
        %table.table
          %thead
            %tr
              %th.text-center Transaction Code
              %th.text-center Transaction Date
              %th.text-center Amount
              %th.text-center New Balance
          %tbody
            - @transactions.each do |transaction|
              - pre_fix_amount = transaction.transaction_type == 'debit' ? '-' : '+'
              %tr
                %td.text-center= "##{transaction.code}"
                %td.text-center= "#{transaction.created_at}"
                %td.text-center= pre_fix_amount + " #{transaction.amount.format}"
                %td.text-center= transaction.updated_balance.format
        %p= paginate @transactions

                

app/views/layouts/application.haml
%html
  %head
    %meta{ content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %title BankingApp
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'

    %link{ href: "https://fonts.googleapis.com/css?family=Poppins&display=swap", rel: "stylesheet" }
    %link{ href: "https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css", rel: "stylesheet" }
    %link{ href: "https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css", rel: "stylesheet" }
  %body
    = yield

app/views/money_transfers/new.haml
.limiter
  .container-login100
    .wrap-login100
      .container
        %h2 Transfer Money
        %p Transfer money to another account, now.
        - if flash[:error].present?
          %p.alert.alert-danger= flash[:error]

        = form_for @money_transfer do |f|
          = f.hidden_field :sender_id
          .input-group.mb-3
            .input-group-prepend
              %span.input-group-text #
            = f.text_field :account_number, class: "form-control", placeholder: "Friend's Account Number"

          .input-group.mb-3
            .input-group-prepend
              %span.input-group-text $
            = f.text_field :amount, class: "form-control", type: "number", placeholder: "Amount"
          .input-group.mb-3
            .input-group-prepend
            = f.text_field :description, class: "form-control", placeholder: "Reason for Transfer"
          .float-right= f.submit "Submit", class: "btn btn-primary"